apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-text-analysis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-text-analysis
  template:
    metadata:
      labels:
        app: fastapi-text-analysis
    spec:
      containers:
        - name: fastapi-text-analysis
          image: pavelgural/fastapi-text-analysis:1.0.0
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 15
          volumeMounts:
            - name: article-examples
              mountPath: /article_examples
      volumes:
        - name: article-examples
          configMap:
            name: article-examples
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-text-analysis
spec:
  selector:
    app: fastapi-text-analysis
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
